### ISSUE TITLE
Incorrect branch name convention

### ISSUE THREAD

**Issue by JaryJay** [zhanc2/shadowsend#2]
In `BEST_PRACTICES.md`, it says

> When picking up a task, if it is not an issue yet, convert it to an issue. Create a branch for it with the following convention: [issue number] (your name) [issue title]
> 
> For example, if Charles was working on issue #3 which was titled "Create player sprite", the branch name would be: `3 (Charles) Create player sprite`

But actually, branch names cannot contain spaces.

Proof:
<img width="505" alt="image" src="https://github.com/zhanc2/shadowsend/assets/47123100/21fb6ae9-ac15-4369-9ba1-404d8abe6da5">

See also: https://stackoverflow.com/questions/6619073/why-cant-a-branch-name-contain-the-space-char

A better branch name convention would be `<name>/<issue number>`, e.g. `charles/14`. Typically you don't need to include the issue title -- you just add the title in your pull request

**Comment by zhanc2** [comment]
Facts
